version: '3.8'

services:
  tradeapi:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    # ports:
    #   - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./bist100_models:/app/bist100_models
      - ./binance_models:/app/binance_models
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tradepi.rule=Host(`tradepi.melikbugraozcelik.com`)"
      - "traefik.http.routers.tradepi.entrypoints=websecure"
      - "traefik.http.routers.tradepi.tls.certresolver=le"
      - "traefik.http.routers.tradepi.middlewares=hsts@file"
      - "traefik.http.services.tradepi.loadbalancer.server.port=5173"

  tradeui:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    # ports:
    #   - "5173:5173"
    environment:
      - VITE_API_HOST=tradeapi
      - VITE_API_URL=${API_URL:-https://tradeapi.melikbugraozcelik.com}
      - VITE_APP_PIN=${APP_PIN:-meliktrade123}
    depends_on:
      - tradeapi
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tradeui.rule=Host(`tradeui.melikbugraozcelik.com`)"
      - "traefik.http.routers.tradeui.entrypoints=websecure"
      - "traefik.http.routers.tradeui.tls.certresolver=le"
      - "traefik.http.routers.tradeui.middlewares=hsts@file"
      - "traefik.http.services.tradeui.loadbalancer.server.port=5173"

networks:
  web:
    external: true
    name: traefik-proxy