FROM node:20-alpine

WORKDIR /app

# Copy UI Code
COPY financia/ui/package.json financia/ui/package-lock.json ./

# Install Deps
RUN npm install

# Copy Source
COPY financia/ui ./

# Expose Port
EXPOSE 5173

# Run with Host 0.0.0.0 so it's accessible outside container
CMD ["npm", "run", "dev", "--", "--host"]
